services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Assure-toi que ce fichier est monté correctement
      - ./staticfiles:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
