services:
  - type: web
    name: tradeflow
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: "python manage.py collectstatic --noinput"
    startCommand: "gunicorn tradeflow.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: tradeflow.settings
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
    healthCheckPath: /healthz


