# Generated by Django 4.2.11 on 2024-11-28 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='save_by',
            field=models.ForeignKey(limit_choices_to={'role': 'M'}, on_delete=django.db.models.deletion.PROTECT, related_name='manager_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_article_name'),
        ),
    ]
