# Generated by Django 4.2.11 on 2024-11-28 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date_time', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('paid', models.BooleanField(default=False)),
                ('invoice_type', models.CharField(choices=[('R', 'RECEIPT'), ('P', 'PROFORMA INVOICE'), ('I', 'INVOICE')], max_length=1)),
                ('comments', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Order_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('total', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('article_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article', to='Article.article')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.invoice')),
            ],
            options={
                'verbose_name': 'Order_line',
                'verbose_name_plural': 'Order_lines',
            },
        ),
    ]
