# Generated by Django 4.2.11 on 2024-11-28 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'role': 'C'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='save_by',
            field=models.ForeignKey(limit_choices_to={'role': 'S'}, on_delete=django.db.models.deletion.CASCADE, related_name='seller_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
