# Generated by Django 4.2.11 on 2024-12-16 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Orders', '0003_alter_invoice_save_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='save_by',
            field=models.ForeignKey(limit_choices_to={'role': ['S', 'A', 'C']}, on_delete=django.db.models.deletion.CASCADE, related_name='seller_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
